### ISSUE TITLE
Can't find iplScoopGenerateModel.py

### ISSUE THREAD

**Issue by xiazaiba7** [NIST-MNI/nist_mni_pipelines#14]
Hello, I was guided from this page 'https://github.com/NIST-MNI/build_average_model', but I can't find iplScoopGenerateModel.py described in this page. Was there a rename?

**Comment by vfonov** [comment]
Yes, I renamed it to `ipl_generate_model.py` , it's also not using scoop anymore, but rather `ray` for parallelization.

**Comment by xiazaiba7** [comment]
Thank you!!!

**Comment by ZOU-Da** [comment]
in [ipl_generate_model.py](https://github.com/NIST-MNI/nist_mni_pipelines/blob/608acff75601bf80f79334abc0434bbc0734af0d/ipl_generate_model.py#L6C19-L6C32), `ScoopGenerateModel‎` was still used. Where is the updated code of `generate model`, in `ipl/longitudinal/generate_model.py`?
If I wanna learn the procedure of generating average atlas, should I follow this python file `generate_model.py`?

**Comment by 7oud** [comment]
in [ipl_generate_model.py](https://github.com/NIST-MNI/nist_mni_pipelines/blob/608acff75601bf80f79334abc0434bbc0734af0d/ipl_generate_model.py#L6C19-L6C32), `ScoopGenerateModel‎` was still used. Where is the updated code of `generate model`, in `ipl/longitudinal/generate_model.py`?
If I wanna learn the procedure of generating average atlas, should I follow this python file `generate_model.py`?

BTW, it is not easy to setup the environment, especially the minc related, could you give some advices, which python scripts are necessary if I don't care about the visualization and UI

**Comment by vfonov** [comment]
oops , looks like i forgot to update the cli version. All the logic for model generation is in https://github.com/NIST-MNI/nist_mni_pipelines/tree/master/ipl/model
